### ISSUE TITLE
InferJavapTest failing in 2.12.7 nightly builds

### ISSUE THREAD

**Issue by SethTisue** [fthomas/refined#569] opened 2018-09-16 00:33 UTC
if I add `resolvers += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"`

and fix the macro paradise version at 2.12.6 since no 2.12.7 build yet exists yet (of course)

```diff
-          ("org.scalamacros" % "paradise" % macroParadiseVersion cross CrossVersion.patch) % configuration
+          ("org.scalamacros" % "paradise_2.12.6" % macroParadiseVersion) % configuration
```

then `++2.12.7-bin-25d596e!` followed by `scalazJVM/test`, I see:

```
[info] ! InferJavapTest.javap -c InferAnyValTest: Falsified after 0 passed tests.
[info] > Labels of failing property: 
[info] Expected "Compiled from "InferJavapSpec.scala"\u000apublic class eu.timepit.refined.scalaz.InferAnyValTest {\u000a  public eu.timepit.refined.scalaz.RefineAnyValTest r();\u000a    Code:\u000a       0: aload_0\u000a       1: getfield      #13                 // Field r:Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       4: areturn\u000a  public int Refined();\u000a    Code:\u000a       0: getstatic     #23                 // Field eu/timepit/refined/api/Refined$.MODULE$:Leu/timepit/refined/api/Refined$;\u000a       3: aload_0\u000a       4: invokevirtual #25                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       7: invokevirtual #29                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.Refined:()Ljava/lang/Integer;\u000a      10: invokevirtual #33                 // Method eu/timepit/refined/api/Refined$.unsafeApply:(Ljava/lang/Object;)Ljava/lang/Object;\u000a      13: checkcast     #35                 // class java/lang/Integer\u000a      16: areturn\u000a  public int shapeless_tag();\u000a    Code:\u000a       0: aload_0\u000a       1: invokevirtual #25                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       4: invokevirtual #39                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.shapeless_tag:()I\u000a       7: invokestatic  #45                 // Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;\u000a      10: invokestatic  #49                 // Method scala/runtime/BoxesRunTime.unboxToInt:(Ljava/lang/Object;)I\u000a      13: ireturn\u000a  public java.lang.Object scalaz_tag();\u000a    Code:\u000a       0: aload_0\u000a       1: invokevirtual #25                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       4: invokevirtual #53                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.scalaz_tag:()Ljava/lang/Object;\u000a       7: areturn\u000a  public int unrefined();\u000a    Code:\u000a       0: aload_0\u000a       1: invokevirtual #25                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       4: invokevirtual #56                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.unrefined:()I\u000a       7: ireturn\u000a  public eu.timepit.refined.scalaz.InferAnyValTest();\u000a    Code:\u000a       0: aload_0\u000a       1: invokespecial #60                 // Method java/lang/Object."<init>":()V\u000a       4: aload_0\u000a       5: new           #27                 // class eu/timepit/refined/scalaz/RefineAnyValTest\u000a       8: dup\u000a       9: invokespecial #61                 // Method eu/timepit/refined/scalaz/RefineAnyValTest."<init>":()V\u000a      12: putfield      #13                 // Field r:Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a      15: return\u000a}" but got "Compiled from "InferJavapSpec.scala"\u000apublic class eu.timepit.refined.scalaz.InferAnyValTest {\u000a  public eu.timepit.refined.scalaz.RefineAnyValTest r();\u000a    Code:\u000a       0: aload_0\u000a       1: getfield      #13                 // Field r:Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       4: areturn\u000a  public int Refined();\u000a    Code:\u000a       0: getstatic     #24                 // Field eu/timepit/refined/api/Refined$.MODULE$:Leu/timepit/refined/api/Refined$;\u000a       3: aload_0\u000a       4: invokevirtual #26                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       7: invokevirtual #30                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.Refined:()Ljava/lang/Integer;\u000a      10: invokevirtual #34                 // Method eu/timepit/refined/api/Refined$.unsafeApply:(Ljava/lang/Object;)Ljava/lang/Object;\u000a      13: checkcast     #36                 // class java/lang/Integer\u000a      16: areturn\u000a  public int shapeless_tag();\u000a    Code:\u000a       0: aload_0\u000a       1: invokevirtual #26                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       4: invokevirtual #39                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.shapeless_tag:()I\u000a       7: invokestatic  #45                 // Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;\u000a      10: invokestatic  #49                 // Method scala/runtime/BoxesRunTime.unboxToInt:(Ljava/lang/Object;)I\u000a      13: ireturn\u000a  public java.lang.Object scalaz_tag();\u000a    Code:\u000a       0: aload_0\u000a       1: invokevirtual #26                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       4: invokevirtual #53                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.scalaz_tag:()Ljava/lang/Object;\u000a       7: areturn\u000a  public int unrefined();\u000a    Code:\u000a       0: aload_0\u000a       1: invokevirtual #26                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a       4: invokevirtual #56                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.unrefined:()I\u000a       7: ireturn\u000a  public eu.timepit.refined.scalaz.InferAnyValTest();\u000a    Code:\u000a       0: aload_0\u000a       1: invokespecial #60                 // Method java/lang/Object."<init>":()V\u000a       4: aload_0\u000a       5: new           #28                 // class eu/timepit/refined/scalaz/RefineAnyValTest\u000a       8: dup\u000a       9: invokespecial #61                 // Method eu/timepit/refined/scalaz/RefineAnyValTest."<init>":()V\u000a      12: putfield      #13                 // Field r:Leu/timepit/refined/scalaz/RefineAnyValTest;\u000a      15: return\u000a}"
```

this turned up in the Scala 2.12 community build at e.g. 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3520/

offhand, it looks like it's probably just a test that's extremely sensitive to compiler details... but could you look and see if you think it's a Scala regression...?

**Comment by SethTisue** [comment] 2018-09-16 00:59
for now, in the community build I've just excluded `InferJavapSpec.scala` and `RefineJavapSpec.scala` (they're both affected I guess actually?), scala/community-builds@054673d1719ac269abf6f67d1580c05bdcf40431 and scala/community-builds@4b653437ec3e14657e3bedba3a46f2a0fed3d56e

**Comment by NeQuissimus** [comment] 2018-10-03 12:09
Here is a diff of the output btw:

```diff
10c10
<        0: getstatic     #23                 // Field eu/timepit/refined/api/Refined$.MODULE$:Leu/timepit/refined/api/Refined$;
---
>        0: getstatic     #24                 // Field eu/timepit/refined/api/Refined$.MODULE$:Leu/timepit/refined/api/Refined$;
12,15c12,15
<        4: invokevirtual #25                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;
<        7: invokevirtual #29                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.Refined:()Ljava/lang/Integer;
<       10: invokevirtual #33                 // Method eu/timepit/refined/api/Refined$.unsafeApply:(Ljava/lang/Object;)Ljava/lang/Object;
<       13: checkcast     #35                 // class java/lang/Integer
---
>        4: invokevirtual #26                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;
>        7: invokevirtual #30                 // Method eu/timepit/refined/scalaz/RefineAnyValTest.Refined:()Ljava/lang/Integer;
>       10: invokevirtual #34                 // Method eu/timepit/refined/api/Refined$.unsafeApply:(Ljava/lang/Object;)Ljava/lang/Object;
>       13: checkcast     #36                 // class java/lang/Integer
20c20
<        1: invokevirtual #25                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;
---
>        1: invokevirtual #26                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;
28c28
<        1: invokevirtual #25                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;
---
>        1: invokevirtual #26                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;
34c34
<        1: invokevirtual #25                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;
---
>        1: invokevirtual #26                 // Method r:()Leu/timepit/refined/scalaz/RefineAnyValTest;
42c42
<        5: new           #27                 // class eu/timepit/refined/scalaz/RefineAnyValTest
---
>        5: new           #28                 // class eu/timepit/refined/scalaz/RefineAnyValTest
```

I think this is just a case of a sensitive test. I have noticed other changes in the bytecode output with 2.12.7 as well.

**Comment by fthomas** [comment] 2018-10-04 08:35
Sorry for the late reply. This does not look like a regression in the compiler, the only things that changed are the constant pool indices. I've already updated the javap output in https://github.com/fthomas/refined/pull/571/files#diff-b1953059626d9d11e6d6164edec0e90b and will modify the tests such that they are not sensitive to these indices.

**Comment by SethTisue** [comment] 2018-10-04 18:39
green at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/, thanks Frank!

you can leave this ticket open if you like, to track the "will modify the tests" part, or close it

**Comment by fthomas** [comment] 2020-09-25 12:19
Closing now because `InferJavapSpec` has been deleted in https://github.com/fthomas/refined/pull/815.

**Closed by fthomas** 2020-09-25 12:19 UTC
